version: 2

analyses:
  - name: revenue
    description: Get product revenue.
    config: &config
      jinjat:
        method: get
        openapi:
          parameters:
            - in: query
              name: grain
              schema:
                type: string
                enum: ['week', 'month']
                default: week
                description: Use this field to filter the data for different granularies.
  - name: profit
    description: Get profit from product subscriptions
    config: *config
  - name: expenses
    description: Get product expenses for all the company
    config: *config
  - name: average_order_amount
    description: Analyze users's average basket data
    config: *config
